eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/learning_spring?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&autoReconnectForPools=true
    initialSize: 20
    maxActive: 60
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    open-in-view: false


